name: "bluebell"
mode: "release"
port: 8080
version: "v0.0.1"
machine_id: 1
start_time: "2020-07-01"

auth:
  jwt_expire: 24
  refresh_expire: 240
log:
  level: "info"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: docker.dxx.com
  port: 33061
  user: "root"
  password: "abc123abc123"
  dbname: "test11"
  max_idle_conns: 2
  max_open_conns: 10
redis:
  host: docker.dxx.com
  port: 6379
  password: "abc123abc123"
  db: 10
  min_idle_conns: 2
  pool_size: 10

#sqlite:
#  dbFilePath: test.db